version: '3.2'

services:
  axum_todo:
    build:
      context: ./${APP_NAME}
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GID}
        USER_NAME: ${UNAME}
        APP_EARTH_PATH: ${APP_EARTH_PATH}
        APP_NAME: ${APP_NAME}
    ports:
      - ${HOST_PORT}:3000
      - 9229:9229
    volumes:
      - ${PWD}/${APP_NAME}:${APP_EARTH_PATH}/${APP_NAME}
    networks:
      axum_todo_net:
        ipv4_address: 172.22.20.20
    user: "${USER_ID}:${GID}"
    environment:
      - RUST_LOG=debug
      - TZ=Asia/Tokyo
    # the third priority DOCKER_HOST
    # environment:
      # - DOCKER_HOST=ssh://${UNAME}@localhost:${SSH_PORT}
networks:
  axum_todo_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.20.0/24
